---
title: 'Behold Your God: Rethinking God Biblically'
subtitle: 'Summer 2023'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: false
---

```{r knitr_setup, include=FALSE, purl=FALSE}
library(knitr)
library(kableExtra)
set.seed(1)
knitr::opts_knit$set(aliases=c(h = 'fig.height', w = 'fig.width'))
knitr::opts_chunk$set(comment="#", message=FALSE, collapse=TRUE, cache=FALSE, tidy=FALSE, fig.align="center")
knitr::knit_hooks$set(small.mar = function(before, options, envir) {
  if (before) par(mar = c(4, 4, .1, .1))
})
```

# Welcome!

This is the landing page for the 2023 summer Bible study course called "Behold Your God." This 13-week course was written and designed by the leaders of [Media Gratiae ](https://www.mediagratiae.org/behold-your-god-rethinking-god-biblically). This study is being offered as a virtual course during summer 2023 through [Grace Community Church Downtown](https://graceb3.org/downtown-campus/) in Iowa City. 

The treasure of the Christian life is knowing God, and the objective of this class is for students to know Him and His character. [Click here to watch a trailer video](https://vimeo.com/51532043) overview of the course. 

## Start here

This study will be offered via [Zoom](zoom.html) on the following Wednesday evenings: 

 - **May**: 24, 31
  
  - **June**: 7, 14, 21, 28 
  
  - **July**: 5, 12, 19, 26
  
  - **August**: 2, 9, and 16
  
All meetings will be held from 7-8:15 pm (CST). These meetings will consist of a 45-55 minute video lecture, followed by 15-20 minutes of discussion. 

To participate in this study, you will need a workbook. The workbook contains questions and Bible texts to study in preparation for each week's lesson. These assignments are not to be submitted to the instructor. 

## Sign up 

To sign up for this course and receive your workbook, please contact Tabitha (the class coordinator) either by text (+1 615 630 5088) or via email at tabitha.peter15@gmail.com. 
The **deadline** to sign up is **Monday, May 15, 2023**. 

The cost for the course is estimated at $20-25/person. The final cost will depend on the total number of students. The leadership at Grace Community Church does not want this cost to prevent anyone from signing up; if the cost is a barrier for you, please contact Tabitha and she will help you get connected. 

## [Zoom meeting information](zoom.html)

Follow the link to this page for the Zoom meeting information. 

## [More information](faq.html)

For more information about this course, check out the FAQs on this page.  

## [Supplementary online materials](materials.html)

Follow this link to see more online materials. Stuff here includes: 

  - Where to find a copy of the Bible 
  
  - Other books/materials that are related to the course (supplemental readings)
